version: "3"
services:
  pg:
    image: "postgres:latest"
    container_name: pg
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
  redis:
    image: "redis:latest"
    container_name: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  pg-data:
  redis-data:
