version: "3"
services:
  pg:
    image: "postgres:latest"
    # container_name: pg
    environment:
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: rainbow_database
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
  redis:
    image: "redis:latest"
    container_name: redis
    environment:
      REDIS_PASSWORD: mysecretpass
      REDIS_TTL: 3600
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  pg-data:
  redis-data:
